apiVersion: v1
kind: Service
metadata:
  name: "account"
  namespace: "kube-public"
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app: "account"
