---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "account"
  namespace: "kube-public"
  labels:
    app: "account"
    version: "1.0"    
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "account"
    spec:
      containers:
      - name: info
        image: https://hub.docker.com/r/artaneja13/account/tags/latest
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "120Mi"
            cpu: "120m"
      restartPolicy: Always