apiVersion: v1
kind: Service
metadata:
  name: "account-deposit"
  namespace: "kube-public"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8083
      protocol: TCP
      targetPort: 8081
  selector:
    app: "account-deposit"
