---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # name: "${APP_NAME}-${ROUTE_OFFER}"
  name: "${APP_NAME}"
  namespace: "${APP_NS}"
  labels:
    app: "${APP_NAME}"
    version: "${VERSION:-0.0.1}"    
spec:
  replicas: ${REPLICA_COUNT}
  selector:
    matchLabels:
      app: "${APP_NAME}"
      version: "${VERSION:-0.0.1}"
      routeoffer: "${ROUTE_OFFER}"
  template:
    metadata:
      annotations:
        GRM_ENV: "${GRM_ENV:-DEV}"
      labels:
        app: "${APP_NAME}"
        version: "${VERSION:-0.0.1}"
        build: "${BUILD_NUMBER:-undefined}"
        commit: "${GIT_COMMIT:-unknown}"
        routeoffer: "${ROUTE_OFFER}"
    spec:
      serviceAccount: "${SERVICE_ACCOUNT:-default}"
      volumes:
      - name: ocnp-cluster-info
        emptyDir: {}
      containers:
      - env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              key: config-env
              name: "${APP_NAME}"
        - name: GET_HOSTS_FROM
          value: dns
        - name: "DNS_DOMAIN"
          value: "cluster.local"
        - name: "HAZELCAST_KUBERNETES_SERVICE_DNS"
          value: "${HZ_APP_NAME:-hazelcast}"
        - name: "HAZELCAST_KUBERNETES_NAMESPACE"
          value: "${APP_NS:-default}"
        - name: DATASOURCE_VALUE
          value: "${DATASOURCE_VALUE:-redis}"
        image: "${IMAGE_NAME}"
        imagePullPolicy: Always
        name: "${APP_NAME}"
        volumeMounts:
        - name: ocnp-cluster-info
          mountPath: /ocnp-cluster-info
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: "2Gi"
            cpu: "250m"
          limits:
            memory: "4Gi"
            cpu: "2"
        args:
        - -cpus
        - "2"
      - name: info
        image: dockercentral.it.att.com:5100/com.att.ocnp.mgmt/cluster-info:1.0
        volumeMounts:
        - name: ocnp-cluster-info
          mountPath: /ocnp-cluster-info
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "120Mi"
            cpu: "120m"
      restartPolicy: Always