look like this:
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: account-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: other
    servicePort: 8080
  rules:
    - host: myweb.com
      http:
        paths:
          - path: /
            backend:
              serviceName: account
              servicePort: 8082
    - host: myweb.com
      http:
        paths:
          - path: /
            backend:
              serviceName: account-deposit
              servicePort: 8083
    - host: myweb.com
        http:
          paths:
              - path: /withdrawal
                backend:
                  serviceName: account-withdrawal
                  servicePort: 8084